version: '3.4'

services:
  nginx:
    image: forsetigithub/nginxsv
    container_name: container-nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/opt/app/
  app:
    image: forsetigithub/itmanagement
    container_name: itmanagement
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    ports:
     - "3000:3000"
    stdin_open: true
    tty: true
  itmanagementwebapi:
    image: forsetigithub/itmanagementwebapi
    container_name: webapi
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: forsetigithub/mssqldb
    container_name: sqlsv1
    hostname: db1
    volumes:
      - C:\Dockerfile\SQLServer\DB:/MSSQL
    ports:
      - 1433:1433      